### ISSUE TITLE
use `client_credentials` grant type

### ISSUE THREAD

**Issue by belfhi** [unconventionaldotdev/flask-multipass-keycloak#1]
If "service accounts roles" is activated in the Keycloak OIDC Client Settings, and adds the appropriate roles to be able to `query-users` and `query-groups`, one can use the `grant_type=client_credentials` in the [request](
https://github.com/unconventionaldotdev/flask-multipass-keycloak/blob/master/src/flask_multipass_keycloak.py#L215) and does not need to add an extra user with the realm roles.

<img width="783" alt="Screenshot 2024-08-28 at 12 53 18" src="https://github.com/user-attachments/assets/8e512c2e-e9fc-4e13-9e82-bea67694ce12">

This would simplify configuration since only `client_id` and `client_secret` needs to be supplied.
More documentation on how the client needs to be set up should be added, though.

**Comment by tomako** [comment]
Thank you @belfhi , I will test this and update the documentation soon.
